export NEUROMTA_ROOT=$PWD
export DRAMSIM3_ROOT=${NEUROMTA_ROOT}/src/externals/dramsim3
export DRAMSIM3_CONFIG_DIR=${DRAMSIM3_ROOT}/configs
export DRAMSIM3_DEFAULT_OUT_DIR=${NEUROMTA_ROOT}/.tmp

mkdir -p ${DRAMSIM3_DEFAULT_OUT_DIR}